### ISSUE TITLE
After some string function calls, either missing '<' at front or extra '>' at the end

### ISSUE THREAD

**Issue by shihch** [gsk-aiops/bellman#103]
For example:
URI(CONCAT("http://lit-search-api/node/doc#", ?docid) 
missed '<' in the result set
while
STRAFTER(str(?d), "#")
has extra '>' at the end since ?d is an URI

**Comment by pepegar** [comment]
Yep, I've noticed this one too.  In order to fix it, we need to change the way we're loading the data.

If we do it _the easy way_ as we're doing now, `nTriplesFileString.split("\n").flatMap(row => row.removeSuffix(" .").split(" ").map(toSPO))`, our dataframe will contain URIs formatted like this:

```
<https://gsk-id.yadda.yadda/id/Document>
```

However, if we use a library such as sansa-rdf or Jena for loading the NT file into a dataframe, the angle brackets are gonna get stripped automatically in all URIs.

I believe the correct approach in this case would be:

1. Load our input dataframes using Jena or sansa-rdf-spark.  This way the data will be _clean_.
2. Change the way we're querying the underlying the dataframe per each triple, and, if any of the positions we need to query by is an URI, strip it from the angle brackets.

I haven't tackled this one before because of the demos @JNKHunter  is conducting, since it's an error prone process.

**Comment by JNKHunter** [comment]
@pepegar demos are done, please proceed with a fix! In our experience the folks on the Sansa-RDF library have a nice clean implementation we could take inspiration/borrow from.
