### ISSUE TITLE
The simple query returns nothing

### ISSUE THREAD

**Issue by shihch** [gsk-aiops/bellman#200]
I include the engine build: `0.1.12+316-fbd5626f-SNAPSHOT`, run a simple query and it returns 0 result:

![image](https://user-images.githubusercontent.com/13775943/114104419-ab787980-987f-11eb-9164-89b48895299a.png)

when I specify default graph in the query and use the same dataframe, I get proper result:

![image](https://user-images.githubusercontent.com/13775943/114104764-5be67d80-9880-11eb-8430-7ac963a551c7.png)

**Comment by JNKHunter** [comment]
@patofp Could we please prioritize this one? And please investigate why this was able to pass unit testing.

**Comment by patofp** [comment]
Ok, I'm pretty sure this is happening because of the `g` column of the dataset. When the value of `g` column is not `""` (an empty string) it means it is not in the default graph, unless explicitly told to add it in the query via FROM. 

This has to do with the concept of how the dataset is constructed, `inclusive` or `exclusive` pointed out in this [blog post](https://blog.metaphacts.com/the-default-graph-demystified). It is a tricky question as there is no spec about how it should be constructed and it is up to the Sparql endpoint on how to do it, `inclusive` or `exclusive`.

So here I must assume my responsibility on this since I couldn't see the big picture and the implications this could have on the construction of the dataset with all the partitioning of the KG in Hudi and the incremental queries.

Said that, I think we should make the engine `inclusive` by default, so all graphs are added to the default graph if not explicitly told to. Right now the engine has an `exclusive` strategy implemented, same as Jena. 

The good news is that I think there is a way to adapt the engine and do it `inclusive` without effort.

Also I think this is worth to discuss in a meeting so we are all aligned, and we all know what `exlcusive` and `inclusive` means and the repercussion of the different strategies it may have and that maybe I'm missing.

What do you think @JNKHunter and @shihch?

**Comment by patofp** [comment]
Ok, I did some testing and I can confirm that it is all about that. The fix to do it `inclusive` is really easy.

**Comment by patofp** [comment]
Also if needed it is possible to keep both strategy and set a configuration flag that will set the engine to adopt an `inclusive` or `exclusive` strategy.

As in #195 we could set configuration flags for this kind of things. To implement this we should know how the query API is running the `bellman/engine` @shihch. A possibility is to set this flags as Java Options on startup. 

This solution may not be very flexible as once the engine is started flags are set and can't be modify. But in further iterations we can think on passing this flags on the API requests so in each query this flags can be setup, is just an idea, don't know if it makes sense from the users point of view.

**Comment by shihch** [comment]
@patofp, quick question: For legacy data, the graph field would be empty strings, does this update handle such a case?

**Comment by patofp** [comment]
> @patofp, quick question: For legacy data, the graph field would be empty strings, does this update handle such a case?

Yes, data with empty string as graph value will be included in the default graph

**Comment by JNKHunter** [comment]
Thanks all.

I'd say we should go with the Jena default (exclusive). This way we have a goto implementation for reference. I really like the idea of a flag to determine inclusive/exclusive.

@shihch thoughts? Objections?

**Comment by shihch** [comment]
@JNKHunter, to set default 'inclusive' would help user's transition from old queries to new data format. Since most of legacy queries do not have 'FROM' clause, the result of queries would be empty on new datasets. However, There is no problem to set 'exclusive' as default as long as we config the engine to be 'inclusive' during the transition period.

**Comment by JNKHunter** [comment]
Very good point @shihch. Let's move forward with inclusive as default.
