### ISSUE TITLE
Remove duplicates from "Construct" query result

### ISSUE THREAD

**Issue by shihch** [gsk-aiops/bellman#321]
Since the result assumes to be a graph of triples. It makes sense to preform this step in the engine.

**Comment by JNKHunter** [comment]
@shihch Are the duplicates the result an error, or just the natural result of the query + construct? I believe it is expected that CONSTRUCT could return duplicates, as long as the duplicates are correct. I found this conversation here:

https://community.stardog.com/t/duplicate-triples-from-construct-queries/2821

If deduplicating the results is a straightforward and performant operation, then let's do it. Otherwise if we are affecting performance, we may want to push deduplication until later.

**Comment by bkosuru** [comment]
@JNKHunter This is related to the performance issue I was working on.
There was 3.3G worth of data that had just the following rows of total 10.9G 

<http://lit-search-api/node/doc#> | <http://lit-search-api/property/docID> | ""

There was 5G worth of data that had just the following rows of total 10.9G 

<http://lit-search-api/node/doc#> | <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> | <http://lit-search-api/node/Document>

**Comment by bkosuru** [comment]
The output dataset had 1,963,652,990 triples with duplicates and 77,437,844 triples after dedup

**Comment by JNKHunter** [comment]
Got it. It's the result of an error.

**Comment by JNKHunter** [comment]
Whoever picks this up please work with Clark or Bindu to toubleshoot.

**Comment by patofp** [comment]
From Jira ticket:

The following query produces 1.8 billion triples and only 77 million are unique

"query": "PREFIX dm: <http://gsk-kg.rdip.gsk.com/dm/1.0/> PREFIX litn: <http://lit-search-api/node/> PREFIX litp: <http://lit-search-api/property/> CONSTRUCT

{ ?Document a litn:Document . ?Document litp:docID ?docid . }
WHERE{ ?d a dm:Document . BIND(STRAFTER(str(?d), \"#\") as ?docid) . BIND(URI(CONCAT(\"http://lit-search-api/node/doc#\", ?docid)) as ?Document) . }",

"inputLocation": "hdfs://test-scc/data/unstructured/integrated/cross_e/aiml/kg_backend_store/dm1.0/hudi/spog"

There is another ticket to remove the duplicates 

https://github.com/gsk-aiops/bellman/issues/321

This ticket is to validate the results of the query. Why there are so many duplicates?
